version: '3.1'
services:
  server:
    build:
      context: .
    links:
      - postgresql
    depends_on:
      postgresql:
          condition: service_healthy
    ports:
      - 3333:3000
    environment:
      - DATABASE_URL=postgresql://root:root@postgresql:5432/twitty?schema=public

  postgresql:
    image: postgres
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=root
    volumes:
      - ./postgresql-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-d", "root"]
      interval: 5s
      timeout: 60s
      retries: 5
